# Generated by Django 5.1.6 on 2025-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('items', models.CharField(choices=[('burger', 'Burger'), ('fries', 'Fries'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('other', 'Other'), ('none', 'None')], default='none', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('paid', 'Paid')], default='pending', max_length=10)),
            ],
        ),
    ]
