# Generated by Django 5.1.6 on 2025-02-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
